import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import SocketProvider from "@/lib/socket/socket-provider";
import ReduxProvider from "@/lib/redux/redux-provider";

import Header from "@/components/header";
import LoginPopup from "@/components/login-popup";
import SignupPopup from "@/components/signup-popup";
import IconPopup from "@/components/icon-popup";
import AddFriendPopup from "@/components/add-friend-popup";
import NotificationsPopup from "@/components/notifications-popup";
import ManageAccountPopup from "@/components/manage-account-popup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "msgME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SocketProvider>
          <ReduxProvider>
            <Header />
            <LoginPopup />
            <SignupPopup />
            <IconPopup />
            <AddFriendPopup />
            <NotificationsPopup />
            <ManageAccountPopup />
            {children}
          </ReduxProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
